// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAagGsEnxNpbKx-oszpopmJmKX6XL0Q8GU',
    appId: '1:825977772000:web:981537a98b3f9aff3a7d85',
    messagingSenderId: '825977772000',
    projectId: 'plant-app-gemini-123',
    authDomain: 'plant-app-gemini-123.firebaseapp.com',
    storageBucket: 'plant-app-gemini-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyqt08PeLdJaHK869xv02U6PqP281iZ4I',
    appId: '1:825977772000:android:3267fbffde7ddc3c3a7d85',
    messagingSenderId: '825977772000',
    projectId: 'plant-app-gemini-123',
    storageBucket: 'plant-app-gemini-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwKDOCzpsAbAgJI1gLLNvE9HzV_5ENaTw',
    appId: '1:825977772000:ios:d6da3b64b756dd1b3a7d85',
    messagingSenderId: '825977772000',
    projectId: 'plant-app-gemini-123',
    storageBucket: 'plant-app-gemini-123.firebasestorage.app',
    iosBundleId: 'com.plantify.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:825977772000:ios:f63116de94e239d43a7d85',
    messagingSenderId: '825977772000',
    projectId: 'plant-app-gemini-123',
    storageBucket: 'plant-app-gemini-123.appspot.com',
    iosClientId:
        '825977772000-8l4i5j0j3v6n4g0p3b2a1s0f9e8d7c6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}